btsync:
  image: jmcarbo/btsync
  command: AE4FT3RMZK6AGYGQEPA2XFOQPMTVW3I7A
  environment:
    #- KNOWN_HOSTS=[ "btsync:55555" ]
    - DATA_DIR=/data1
    - USE_TRACKER=true
    - USE_DHT=false
    - USE_RELAY_SERVER=false
    - SEARCH_LAN=true
  volumes:
    - data1:/data1

btsync2:
  image: jmcarbo/btsync
  command: AE4FT3RMZK6AGYGQEPA2XFOQPMTVW3I7A
  environment:
    #- KNOWN_HOSTS=[ "btsync:55555" ]
    - DATA_DIR=/data2
    - USE_TRACKER=true
    - USE_DHT=false
    - USE_RELAY_SERVER=false
    - SEARCH_LAN=true
  volumes:
    - data2:/data2
