#!/bin/bash

newSecret() {
  echo "$(btsync --generate-secret)"
}

configBTSync() {
  local secret="$1"
  secret=${secret:-$(newSecret)} 


  echo "{
      \"device_name\": \"Sync Server\",
      \"listening_port\": 55555,
      \"storage_path\": \"/btsync/.sync\",
      \"pid_file\": \"/var/run/btsync/btsync.pid\",
      \"check_for_updates\": false,
      \"use_upnp\": false,
      \"download_limit\": 0,
      \"upload_limit\": 0,
      \"shared_folders\": [
          {
              \"secret\": \"$secret\",
              \"dir\": \"/data\",
              \"use_relay_server\": true,
              \"use_tracker\": true,
              \"use_dht\": false,
              \"search_lan\": true,
              \"use_sync_trash\": true,
              \"known_hosts\": [ \"btsync1:55555\", \"btsync2:55555\" ] 
          }
      ]
  }" 
}

main() {
	set -eo pipefail
	case "$1" in
	new-secret)         
    newSecret
    ;;
	test)                  
    shift
    echo "Starting btsync with secret: $secret"
    configBTSync "$@"
    ;;
  *)
    echo $(configBTSync "$@") > /btsync/btsync.conf
    grep secret /btsync/btsync.conf
    btsync --config /btsync/btsync.conf --nodaemon
    ;;
	esac
}

main "$@"
