#!/bin/bash

newSecret() {
  echo "$(btsync --generate-secret)"
}

configBTSync() {
  local secret="$1"
  secret=${secret:-$(newSecret)} 
  data_dir=${DATA_DIR:-/data} 
  use_tracker=${USE_TRACKER:-true}
  use_dht=${USE_DHT:-false}
  use_relay_server=${USE_RELAY_SERVER:-true}
  search_lan=${SEARCH_LAN:-true}
  hostname=${HOSTNAME:-$(hostname)}
  known_hosts=${KNOWN_HOSTS:-[ ]}


  echo "{
      \"device_name\": \"$hostname\",
      \"listening_port\": 55555,
      \"storage_path\": \"/btsync/.sync\",
      \"pid_file\": \"/var/run/btsync/btsync.pid\",
      \"check_for_updates\": false,
      \"use_upnp\": false,
      \"download_limit\": 0,
      \"upload_limit\": 0,
      \"shared_folders\": [
          {
              \"secret\": \"$secret\",
              \"dir\": \"$data_dir\",
              \"use_relay_server\": $use_relay_server,
              \"use_tracker\": $use_tracker,
              \"use_dht\": $use_dht,
              \"search_lan\": $search_lan,
              \"use_sync_trash\": true,
              \"known_hosts\": $known_hosts 
          }
      ]
  }" 
}

main() {
	set -eo pipefail
	case "$1" in
	new-secret)         
    newSecret
    ;;
	test)                  
    shift
    echo "Starting btsync with secret: $secret"
    configBTSync "$@"
    ;;
  *)
    echo $(configBTSync "$@") > /btsync/btsync.conf
    grep secret /btsync/btsync.conf
    btsync --config /btsync/btsync.conf --nodaemon
    ;;
	esac
}

main "$@"
